### ISSUE TITLE
Advanced ambient widget

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#22]
- [ ] LouisCaerts/Procrastination-MP-final-web-app#5
- [ ] LouisCaerts/Procrastination-MP-final-web-app#4
- [ ] LouisCaerts/Procrastination-MP-final-web-app#3
