### ISSUE TITLE
Basic ambient widget

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#23]
- [ ] LouisCaerts/Procrastination-MP-final-web-app#9
- [ ] LouisCaerts/Procrastination-MP-final-web-app#8
- [ ] LouisCaerts/Procrastination-MP-final-web-app#7
- [ ] LouisCaerts/Procrastination-MP-final-web-app#6
