### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#25]
- [ ] LouisCaerts/Procrastination-MP-final-web-app#2
- [ ] LouisCaerts/Procrastination-MP-final-web-app#1
- [ ] LouisCaerts/Procrastination-MP-final-web-app#14
- [ ] LouisCaerts/Procrastination-MP-final-web-app#13
- [ ] LouisCaerts/Procrastination-MP-final-web-app#12

**Comment by LouisCaerts** [comment]
Based on previous research we will most likely use Supabase's free tier for convenience reasons.
