### ISSUE TITLE
Review experiment data

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#26]
- [ ] LouisCaerts/Procrastination-MP-final-web-app#17
- [ ] LouisCaerts/Procrastination-MP-final-web-app#16
- [ ] LouisCaerts/Procrastination-MP-final-web-app#15
