### ISSUE TITLE
Review GitHub

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#27]
- [x] LouisCaerts/Procrastination-MP-final-web-app#21
- [x] LouisCaerts/Procrastination-MP-final-web-app#20
- [x] LouisCaerts/Procrastination-MP-final-web-app#19
- [x] LouisCaerts/Procrastination-MP-final-web-app#18
