### ISSUE TITLE
Add identity management

### ISSUE THREAD

**Issue by LouisCaerts** [LouisCaerts/Procrastination-MP-final-web-app#33]
- [ ] LouisCaerts/Procrastination-MP-final-web-app#32
- [ ] LouisCaerts/Procrastination-MP-final-web-app#31
- [ ] LouisCaerts/Procrastination-MP-final-web-app#30
- [ ] LouisCaerts/Procrastination-MP-final-web-app#29
- [ ] LouisCaerts/Procrastination-MP-final-web-app#28

**Comment by LouisCaerts** [comment]
**Research on possible identity management integrations**
I briefly looked at all the authentication integrations supported by Netlify by default and my thoughts/findings were as follows:

1. Okta's Auth0
Seems like a powerful API but that also means that is harder to navigate and perhaps overengineered for what we need it for. It seems more focused on roles authentication rather than a custom login experience but this is only based on very brief research. Personally, I wasn't feeling this one.

2. Clerk
This one is the most promising I think. It is definitely customizable and has easy to find/read instructions on how to do that customization. It advertises its Supabase support (a database we might end up using) and has great docs. It feels like a newer/younger/hipper service that still has something to prove and is doing the work to prove it. This was my favorite and the first I'll try developing with. I'll only switch to another if I can't get Clerk to work.

3. Stytch
This was also promising but not quite as much as Clerk. The docs were good but I couldn't find exactly what I need as easily. This will be my second choice if I can't get Clerk to work.

4. Netlify Identity
For some reason this is not advertised on Netlify's integrations page but it is given as an option in other areas of Netlify's dashboard. It seems much more minimal than the other APIs and just didn't give me as good of a feeling. It's not Netlify's primary focus so I'll opt for an API that truly focuses on authentication instead.

**Comment by LouisCaerts** [comment]
After playing around with Clerk, I actually couldn't immediately find a way to add custom fields to signup. Same with Stytch. I took another look at Okta's Auth0 instead and they actually have documentation specifically for adding custom fields during signup.
I have contacted Clerk's support to ask if it is possible to add custom fields but until then I'll leave authentication for what it is and work on other things instead.

**Comment by LouisCaerts** [comment]
Update: Okta's Auth0 also seems to be better supported by Netlify actually. For now Auth0 is the front runner. I have set up the connection between Auth0 and Netlify as well as a blank signup/login page. will continue later with trying to set up a (custom) sign up module and successfully registering a first user.

**It's looking like I will need database support for this, so database and identity quests will most likely continue in tandem from here on out.**
